site_name: coverage-reporter

strict: true

theme:
  name: "material"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - "index.md"
  - "User guide":
      - "user-guide/authentication.md"
      - "user-guide/installation.md"
      - "user-guide/multiple-reports.md"
  - "Troubleshooting":
      - "Commit detection": "troubleshooting/commit-detection.md"
      - "Swift & Objective-C support": "troubleshooting/swift-objectivec.md"
